const CONFIG = {
    introTitle: 'Hê lô nơm',
    introDesc: `T hỏi cái này,trả lời thật lòng',
    btnIntro: 'oke',
    title: 'm yêu t có phải không 😙',
    desc: 'm không trả lời hoặc thoát ra, tức là m ghét t :>',
    btnYes: 'yêu ơi là iuuu <33',
    btnNo: 'ngáo à ',
    question:'Nói cho tới lý do vì sao m thích t :) ',
    btnReply: 'Gửi cho t ',
    reply: 'Tại vì t xinh vl ',
    mess: 'cám ơn nha ngại ghê ',
    messDesc: 'còn giờ thì cút,bố m đi xem phim nha yêu đương đb ',
    btnAccept: 'Ok<3 ',
   
